---
- hosts: "{{ hosts_prompt }}"
  gather_facts: no
  
  vars_prompt:
   - name: "hosts_prompt" ## Host where playbook about to play
     prompt: "Enter the Host or Host group need to run with this Playbook"
     private: no

  tasks:

  - name: Restarting the servers...
    shell: "sleep 5 && reboot"
    async: 1
    poll: 0
 
  - name: Wait for the reboot to complete...
    wait_for_connection:
      connect_timeout: 20
      sleep: 5
      delay: 5
      timeout: 300
